name: EC2 deployement

on: 

   push:

     branches:

       - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: checking-out code

      uses: actions/checkout@v4

    - name: looking into the runner machine

      run: ls
